### ISSUE TITLE
Not working kodi 20.0 (Nexus)

### ISSUE THREAD

**Issue by virtuacool** [highlandr/service.subtitles.legendasdivx#17]
The add-on does not work for me in kodi 20.0, always shows me no results.

**Comment by tfouto** [comment]
Meanwhile you can use this version modified by me.
works on Nexus and was speed optimized by chatgpt.  +/- 4x fastest. 

https://mega.nz/file/oPQQhRqA#n-KND1QZStkzSJ2tyQTtLAy_r2BZOBOhJiOZ2R_p3NU

**Comment by highlandr** [comment]
Fixed here, now I need to send it to the official addon.
